# Generated by Django 4.2.4 on 2024-10-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_workexperience_project_education_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1234, upload_to='profile_media'),
            preserve_default=False,
        ),
    ]
